### ISSUE TITLE
Do not use Google's reCAPTCHA

### ISSUE THREAD

**Issue by locness3** [ideoxan/ideoxan#102]
Having Google's reCAPTACHA on multiple websites is one of the ways google use to track everyone around the web. Would be great to avoid that, there are alternatives.

**Comment by micahlt** [comment]
@locness3 reCAPTCHA is the most prominent, full-featured, versatile, adaptive, and accessible Captcha library available.  You have no evidence that Google is tracking users.  Yes, reCAPTCHA detects if a user has a Google account or not, but by having one in the first place you're giving up a certain amount of privacy.   I understand you're a fan of decentralized tech, and that's fine, but there's no such thing as complete anonymity on the Internet.  Why sacrifice a good UX?  Ideoxan already uses Material Icons hosted on Google's servers.

**Comment by Skyclo** [comment]
We use reCAPTCHA solely due to the fact that it was the most prominent, well documented, cheapest, and easiest to use captcha service available at the time. It was suggested by one of our contributors to help mitigate spam. If you have questions regarding your privacy, please see our Privacy Policy and Google reCAPTCHA's Privacy Policy. Information collected, analyzed, or otherwise distributed among 3rd parties is outlined in these documents. While we respect your concern about privacy, this website is focused on programming, not tracking its users. 

*However*, that being said, if you have any other alternatives that are free, easy to use, and is less privacy invasive, then by all means please feel free to offer suggestions.

**Comment by locness3** [comment]
> You have no evidence that Google is tracking users.
I don't completely agree with that.

Though, hCaptcha seems to be a great alternative.

**Comment by Skyclo** [comment]
> > You have no evidence that Google is tracking users.
>
> I don't completely agree with that.
> 
> Though, hCaptcha seems to be a great alternative.

I'll take a look at it.

**Comment by Skyclo** [comment]
Captchas are no longer used on the new website, so, this is no longer and issue. Cloudflare's reaction to botted requests along with other server-side security measures should be enough to mitigate botted attacks.
